# Generated by Django 6.0.7 on 2026-09-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_staffprofile_lastpasswordchangedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelot',
            name='extraFields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
