# Generated by Django 6.0.7 on 2026-09-01 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_invoicelot_extrafields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='publicToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='managerNote',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='managerVerifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='managerVerifiedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiptFile',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='submittedViaPublicLink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='verificationStatus',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending_manager_review', 'Pending Manager Review'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected')], default='not_applicable', max_length=30),
        ),
    ]
