# Generated by Django 6.0.7 on 2026-09-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_importbatch_columnmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='columnMapping',
            field=models.JSONField(blank=True, default=dict, help_text="Snapshot of which original spreadsheet column supplied each known field for this batch, e.g. {'lotNumber': 'Lot No', 'auctionName': 'Auction', ...}. Captured at import time so it stays accurate for this batch even if the alias list changes later."),
        ),
    ]
