# Generated by Django 6.0.7 on 2026-09-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_alter_importbatch_columnmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='callNotes',
            field=models.TextField(blank=True, default='', help_text='Call Center follow-up note - single mutable field, not a history log.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('telebirr', 'Telebirr'), ('cpo', 'CPO'), ('other', 'Other'), ('unspecified', 'Unspecified')], max_length=20),
        ),
    ]
