# Generated by Django 6.1 on 2026-09-20 12:57

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_invoice_publictoken_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receiptFile',
            field=models.FileField(blank=True, null=True, upload_to=invoices.models.receipt_upload_path),
        ),
    ]
