# Generated by Django 6.0.7 on 2026-09-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_invoice_smssendcount_invoice_smssentat_smslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-sentAt']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='letterData',
            field=models.JSONField(blank=True, default=dict, help_text='Values entered when the invoice PDF was last generated; reused by the public PDF so bidders see the same letter.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actionType',
            field=models.CharField(blank=True, choices=[('change_status', 'Status changed'), ('generate_invoice_pdf', 'Generate invoice PDF'), ('extend_due_date', 'Extend due date'), ('upload_payment', 'Payment uploaded'), ('add_call_note', 'Call center note updated'), ('send_sms', 'SMS sent'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
