# Generated by Django 6.1 on 2026-09-25 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_operations_privilege_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(blank=True, default='', max_length=50)),
                ('receiptNumber', models.CharField(blank=True, default='', max_length=100)),
                ('extractedDate', models.CharField(blank=True, default='', help_text='As printed on the receipt — no calendar conversion is done, may be Ethiopian or Gregorian.', max_length=100)),
                ('customerName', models.CharField(blank=True, default='', max_length=255)),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vatAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('extractionConfidence', models.CharField(blank=True, default='', max_length=20)),
                ('rawResponse', models.JSONField(blank=True, default=dict)),
                ('extractedAt', models.DateTimeField(auto_now_add=True)),
                ('extractedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='invoices.payment')),
            ],
        ),
    ]
