# Generated by Django 6.0.7 on 2026-09-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0032_grant_upload_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptextraction',
            name='convertedGregorianDate',
            field=models.CharField(blank=True, default='', help_text="Best-effort Ethiopian->Gregorian conversion of extractedDate, ISO format. Empty if extractedDate wasn't a parseable, plausible dd/mm/yy(yy) Ethiopian date.", max_length=20),
        ),
    ]
