# Generated by Django 6.0.7 on 2026-09-26 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_receiptextraction_convertedgregoriandate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptextraction',
            name='bankReferenceNumber',
            field=models.CharField(blank=True, default='', help_text='Bank transfer / transaction reference printed on the receipt, distinct from the receipt or invoice number. Used to pre-fill Verify.ET checks.', max_length=100),
        ),
        migrations.CreateModel(
            name='VerifyEtCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, default='', max_length=30)),
                ('referenceNumber', models.CharField(max_length=100)),
                ('accountSuffix', models.CharField(blank=True, default='', max_length=20)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=20)),
                ('requestId', models.CharField(blank=True, default='', max_length=100)),
                ('processingStatus', models.CharField(blank=True, default='', max_length=20)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('senderName', models.CharField(blank=True, default='', max_length=255)),
                ('receiverName', models.CharField(blank=True, default='', max_length=255)),
                ('receiverAccount', models.CharField(blank=True, default='', max_length=100)),
                ('settlementMatched', models.BooleanField(blank=True, null=True)),
                ('rawResponse', models.JSONField(blank=True, default=dict)),
                ('errorMessage', models.TextField(blank=True, default='')),
                ('checkedAt', models.DateTimeField(auto_now_add=True)),
                ('checkedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verifyEtCheck', to='invoices.payment')),
            ],
        ),
    ]
