# Generated by Django 6.0.7 on 2026-09-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0035_grant_view_paid_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.CharField(max_length=40, unique=True)),
                ('lastUsed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
