# Generated by Django 6.0.7 on 2026-09-26 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0036_tokenactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenactivity',
            name='lastUsed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
