# Generated by Django 6.0.7 on 2026-09-27 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0037_alter_tokenactivity_lastused'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='autoReviewed',
            field=models.BooleanField(default=False, help_text="True if this payment's status was set automatically by Verify.ET automation, not a human manager."),
        ),
        migrations.AddField(
            model_name='receiptextraction',
            name='detectedBank',
            field=models.CharField(blank=True, default='', help_text="AI's best guess at the Verify.ET bank code (cbe, telebirr, boa, ...), or blank if unclear.", max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actionType',
            field=models.CharField(blank=True, choices=[('change_status', 'Status changed'), ('generate_invoice_pdf', 'Generate invoice PDF'), ('extend_due_date', 'Extend due date'), ('upload_payment', 'Payment uploaded'), ('add_call_note', 'Call center note updated'), ('send_sms', 'SMS sent'), ('auto_verify_et', 'Auto-verified by Verify.ET'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.CreateModel(
            name='VerifyEtAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoVerificationEnabled', models.BooleanField(default=False)),
                ('configuredAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('configuredBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
