# Generated by Django 6.0.7 on 2026-09-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0038_payment_autoreviewed_receiptextraction_detectedbank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bidderAccountSuffix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='bidderBank',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='bidderPhoneNumber',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='bidderReferenceNumber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
