# Generated by Django 6.0.7 on 2026-09-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0039_payment_bidderaccountsuffix_payment_bidderbank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptextraction',
            name='detectedPhoneNumber',
            field=models.CharField(blank=True, default='', help_text='Sender phone number seen on a Telebirr/CBE Birr receipt, used for wallet verification. Blank if not shown.', max_length=20),
        ),
    ]
