# Generated by Django 6.0.7 on 2026-09-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0040_receiptextraction_detectedphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bidderAccountSuffix',
            field=models.CharField(blank=True, default='', help_text="Last 8 digits of the bidder's account, computed server-side from the full account number they typed — never typed directly by the bidder.", max_length=20),
        ),
    ]
