# Generated by Django 6.0.7 on 2026-09-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0041_alter_payment_bidderaccountsuffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyetcheck',
            name='possibleDuplicate',
            field=models.BooleanField(default=False, help_text='True if this bank+referenceNumber combination was already verified and approved against a different payment — a real transaction reference reused across invoices.'),
        ),
    ]
