# Generated by Django 6.0.7 on 2026-09-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0042_verifyetcheck_possibleduplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyetcheck',
            name='pendingDuplicate',
            field=models.BooleanField(default=False, help_text='True if this bank+referenceNumber also appears on a different PENDING (not yet reviewed) payment — a weaker signal than possibleDuplicate.'),
        ),
        migrations.AlterField(
            model_name='verifyetcheck',
            name='possibleDuplicate',
            field=models.BooleanField(default=False, help_text='True if this bank+referenceNumber is already tied to a different, ALREADY-APPROVED payment.'),
        ),
    ]
