# Generated by Devin manually - for Payment.amountDiscrepancy, Payment.amountDiscrepancyAmount, PaymentReceiptFile, SystemAuditLog
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0044_grant_manage_fee_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amountDiscrepancy',
            field=models.CharField(blank=True, choices=[('underpaid', 'Underpaid'), ('overpaid', 'Overpaid')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='amountDiscrepancyAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='PaymentReceiptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/%Y/%m/%d')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_files', to='invoices.payment')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('performedByName', models.CharField(blank=True, default='', max_length=150)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('performedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
