# Generated by Django 6.1 on 2026-09-29 14:33

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0045_payment_amount_discrepancy_paymentreceiptfile_systemauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceiptfile',
            name='file',
            field=models.FileField(upload_to=invoices.models.receipt_upload_path),
        ),
    ]
