# Generated by Django 6.1 on 2026-09-29 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0047_payment_autoprocessnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyetcheck',
            name='countsAsUsed',
            field=models.BooleanField(default=False, help_text='True when this check backs an approved payment or a credited underpaid partial — locks the reference from reuse.'),
        ),
        migrations.AddConstraint(
            model_name='verifyetcheck',
            constraint=models.UniqueConstraint(condition=models.Q(('countsAsUsed', True)), fields=('bank', 'referenceNumber'), name='unique_used_verify_et_reference'),
        ),
    ]
