# Generated by Django 6.0.7 on 2026-09-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0048_verifyetcheck_countsasused_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bidderAccountSuffix',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bidderBank',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bidderPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bidderReferenceNumber',
        ),
    ]
