# Generated by Django 6.0.7 on 2026-09-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0049_remove_dead_bidder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='escalatedAt',
            field=models.DateTimeField(blank=True, help_text='When the automated overdue escalation reminder was last sent, so it fires once and not repeatedly.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='writeOffReason',
            field=models.TextField(blank=True, default='', help_text='Why this invoice was written off — required, and kept on the record permanently.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('invoice_generated', 'Invoice Generated'), ('pending_payment', 'Pending Payment'), ('payment_submitted', 'Payment Submitted'), ('under_verification', 'Under Verification'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('waived', 'Waived'), ('written_off', 'Written Off')], default='invoice_generated', max_length=20),
        ),
    ]
